MSSA.Canvas-Your-Goals/Models/Tasks/EfTaskRepository.cs
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace MSSA.Canvas_Your_Goals.Models
{
    public class EfTaskRepository : ITaskRepository
    {
        // fields
        private AppDbContext _context;
        private IUserRepository _userRepository;


        // constructors
        public EfTaskRepository(AppDbContext context, IUserRepository userRepository)
        {
            _context = context;
            _userRepository = userRepository;
        } // EfTaskRepository const ends

        
        // methods
        //// create
        public Task CreateTask(Task task)
        {
            if (_userRepository.IsUserLoggedIn())
            {
                _context.Tasks.Add(task);
                _context.SaveChanges();
                return task;
            }
            return null;
        } // CreateTask method ends


        //// read
        public IQueryable<Task> GetAllTasks(int goalId)
        {
            if (_userRepository.IsUserLoggedIn())
            {
                return _context.Tasks.Where(t => t.Goal.UserId == _userRepository.GetLoggedInUserId());
            }
            Task[] noTasks = new Task[0];
            return noTasks.AsQueryable();
        } // GetAllTasks method ends

        public Task GetTaskById(int taskId)
        {
            if (_userRepository.IsUserLoggedIn())
            {
                Task task = _context.Tasks
                    .Include(t => t.Steps)
                    .FirstOrDefault(t => t.TaskId == taskId && t.Goal.UserId == _userRepository.GetLoggedInUserId());
                if (task != null)
                {
                    task.Steps = task.Steps.OrderBy(s => s.StepOrder);
                }
                return task;
            }
            return null;
        } // GetTaskById method ends


        //// update
        public Task UpdateTask(Task task)
        {
            Task taskToUpdate = GetTaskById(task.TaskId);
            if (taskToUpdate != null)
            {
                taskToUpdate.TaskName = task.TaskName;
                taskToUpdate.TaskOrder = task.TaskOrder;
                taskToUpdate.Status = task.Status;
                taskToUpdate.StartDate = task.StartDate;
                taskToUpdate.EndDate = task.EndDate;
                taskToUpdate.Details = task.Details;
                _context.SaveChanges();
            }
            return taskToUpdate;
        } // UpdateTask method ends


        //// delete
        public bool DeleteTask(Task task)
        {
            Task taskToDelete = GetTaskById(task.TaskId);
            if (taskToDelete == null)
            {
                return false;
            }
            _context.Tasks.Remove(taskToDelete);
            _context.SaveChanges();
            return true;
        } // DeleteTask method ends
    } // class ends
} // namespace ends

MSSA.Canvas-Your-Goals/Models/Tasks/ITaskRepository.cs
using System.Linq;

namespace MSSA.Canvas_Your_Goals.Models
{
    public interface ITaskRepository
    {
        // create
        public Task CreateTask(Task addTask);

        // read
        public IQueryable<Task> GetAllTasks(int goalId);

        public Task GetTaskById(int taskId);


        // update
        public Task UpdateTask(Task task);


        // delete
        public bool DeleteTask(Task task);

    }
}

MSSA.Canvas-Your-Goals/Models/Tasks/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;

namespace MSSA.Canvas_Your_Goals.Models
{
    [Table("Task")]
    public class Task
    {
        [HiddenInput(DisplayValue = false)]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TaskId { get; set; }

        [HiddenInput(DisplayValue = false)]
        //- [ForeignKey(nameof(Goal.GoalId))]
        public int GoalId { get; set; }

        public Goal Goal { get; set; }

        public IEnumerable<Step> Steps { get; set; }


        [MaxLength(30, ErrorMessage = "Task Name is Limited to 30 total characters")]
        [Required(ErrorMessage = "A Name is Required")]
        public string TaskName { get; set; }

        public int? TaskOrder { get; set; }

        public string Status { get; set; }

        [DataType(DataType.Date), Required(ErrorMessage = "A Start Date is Required")]
        public DateTime StartDate { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        [DataType(DataType.MultilineText)]
        [MaxLength(2000, ErrorMessage = "Details is Limited to 2000 characters")]
        public string Details { get; set; }
    } // class ends
} // namespace ends

MSSA.Canvas-Your-Goals/Controllers/StepController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MSSA.Canvas_Your_Goals.Models;

namespace MSSA.Canvas_Your_Goals.Controllers
{
    public class StepController : Controller
    {
        // fields
        private IStepRepository _repos;


        // constructors
        public StepController(IStepRepository repository)
            => _repos = repository;
        // StepController const ends


        // methods
        //// Create
        [HttpGet]
        public IActionResult Add(int taskId)
            => View(new Step
            {
                TaskId = taskId, 
                StartDate = DateTime.Now.Date
            });
        [HttpPost]
        public IActionResult Add(Step step)
        {
            if (ModelState.IsValid)
            {
                _repos.CreateStep(step);
                return RedirectToAction("Details", new {stepId = step.StepId});
            }
            return View(step);
        } // Register method ends


        //// Read
        public IActionResult Details(int stepId)
        {
            Step step = _repos.GetStepById(stepId);
            if (step != null)
            {
                return View(step);
            }
            return RedirectToAction("Index", "User");
        } // Details method ends


        //// Update
        [HttpGet]
        public IActionResult Edit(int stepId)
        {
            Step step = _repos.GetStepById(stepId);
            if (step != null)
            {
                return View(step);
            }
            return RedirectToAction("Index", "User");
        } // Edit HttpGet method ends
        [HttpPost]
        public IActionResult Edit(Step step)
        {
            if (step.StartDate > step.EndDate)
            {
                ModelState.AddModelError("", "Start Date must be older than the End Date");
            }
            if (ModelState.IsValid)
            {
                _repos.UpdateStep(step);
                return RedirectToAction("Details", new {stepId = step.StepId});
            }
            return View(step);
        } // Edit method ends


        //// Delete
        [HttpGet]
        public IActionResult Delete(int stepId)
        {
            Step step = _repos.GetStepById(stepId);
            if (step != null)
            {
                return View(step);
            }
            return RedirectToAction("Index", "User");
        } // Delete HttpGet method ends
        [HttpPost]
        public IActionResult Delete(Step step)
        {
            _repos.DeleteStep(step);
            return RedirectToAction("Index", "Goal");
        } // Delete HttpPost method ends
    } // class ends
} // namespace ends

MSSA.Canvas-Your-Goals/Controllers/TaskController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MSSA.Canvas_Your_Goals.Models;

namespace MSSA.Canvas_Your_Goals.Controllers
{
    public class TaskController : Controller
    {
        // fields
        private ITaskRepository _repos;


        // constructors
        public TaskController(ITaskRepository repository)
            => _repos = repository;
        // TaskController const ends


        // methods
        //// Create
        [HttpGet]
        public IActionResult Add(int goalId)
            => View(new Task
            {
                GoalId = goalId, 
                StartDate = DateTime.Now.Date
            });
        [HttpPost]
        public IActionResult Add(Task task)
        {
            if (ModelState.IsValid)
            {
                _repos.CreateTask(task);
                return RedirectToAction("Details", new {taskId = task.TaskId});
            }
            return View(task);
        } // Register method ends


        //// Read
        public IActionResult Details(int taskId)
        {
            Task task = _repos.GetTaskById(taskId);
            if (task != null)
            {
                return View(task);
            }
            return RedirectToAction("Index", "User");
        } // Details method ends


        //// Update
        [HttpGet]
        public IActionResult Edit(int taskId)
        {
            Task task = _repos.GetTaskById(taskId);
            if (task != null)
            {
                return View(task);
            }
            return RedirectToAction("Index", "User");
        } // Edit HttpGet method ends
        [HttpPost]
        public IActionResult Edit(Task task)
        {
            if (task.StartDate > task.EndDate)
            {
                ModelState.AddModelError("", "Start Date must be older than the End Date");
            }
            if (ModelState.IsValid)
            {
                _repos.UpdateTask(task);
                return RedirectToAction("Details", new {taskId = task.TaskId});
            }
            return View(task);
        } // Edit method ends


        //// Delete
        [HttpGet]
        public IActionResult Delete(int taskId)
        {
            Task task = _repos.GetTaskById(taskId);
            if (task != null)
            {
                return View(task);
            }
            return RedirectToAction("Index", "User");
        } // Delete HttpGet method ends
        [HttpPost]
        public IActionResult Delete(Task task)
        {
            _repos.DeleteTask(task);
            return RedirectToAction("Index", "Goal");
        } // Delete HttpPost method ends
    } // class ends
} // namespace ends

MSSA.Canvas-Your-Goals/Views/Task/Add.cshtml
@model MSSA.Canvas_Your_Goals.Models.Task

@{
    ViewData["Title"] = "Add Task";
}

<fieldset class="shadow centered">
    <legend> @ViewData["Title"] </legend>
    <form method="post">
        <input asp-for="TaskId" type="hidden" />
        <input asp-for="GoalId" type="hidden" />
        <table class="table-bordered table-striped table-sm">
            @if (ViewData.ModelState.ErrorCount > 0)
            {
                <thead>
                    <tr>
                        <td colspan="2">
                            <div asp-validation-summary="All"> </div>
                        </td>
                    </tr>
                </thead>
            }
            <tbody>
                <tr>
                    <th> Task Name: </th>
                    <td> <input asp-for="TaskName" /> </td>
                </tr>
                <tr>
                    <th> Task Order: </th>
                    <td> <input asp-for="TaskOrder" type="number" /> </td>
                </tr>
                <tr>
                    <th> Status: </th>
                    <td>
                        <select asp-for="Status">
                            <option value=""> - Select - </option>
                            <option value="Finished">Finished</option>
                            <option value="In Progress">In Progress</option>
                            <option value="Problem">Problem</option>
                            <option value="Waiting">Waiting</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th> Start Date: </th>
                    <td> <input asp-for="StartDate" type="date" /> </td>
                </tr>
                <tr>
                    <th> End Date: </th>
                    <td> <input asp-for="EndDate" type="date" /> </td>
                </tr>
                <tr>
                    <th> Details: </th>
                    <td> @Html.EditorFor(model => model.Details) </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td class="text-center" colspan="2">
                        <input class="btn btn-primary ml-1 mr-1" type="submit" value="Create Task!" />
                        <a class="btn btn-secondary ml-1 mr-1" asp-controller="Goal" asp-action="Details" asp-route-goalId="@Model.GoalId">
                            Cancel
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</fieldset>

MSSA.Canvas-Your-Goals/Views/Task/Delete.cshtml
@model MSSA.Canvas_Your_Goals.Models.Task

@{
    ViewData["Title"] = "Delete Task";
}

<fieldset class="shadow centered">
    <legend> @ViewData["Title"] </legend>
    <table class="table-bordered table-striped table-sm">
        <tbody>
            <tr>
                <th> Goal Name: </th>
                <td> @Model.TaskName </td>
            </tr>
            <tr>
                <th> Priority: </th>
                <td> @Model.TaskOrder </td>
            </tr>
            <tr>
                <th> Status: </th>
                <td> @Model.Status </td>
            </tr>
            <tr>
                <th> Type: </th>
                <td> @Model.StartDate.ToString("MM/dd/yyyy") </td>
            </tr>
            <tr>
                <th> Start Date: </th>
                <td> @Model.EndDate?.ToString("MM/dd/yyyy") </td>
            </tr>
            <tr>
                <td class="text-center btn-outline-warning" colspan="2">
                    <h2> Are You Sure? </h2>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td class="text-center" colspan="2">
                    <form method="post">
                        <input type="hidden" asp-for="TaskId" />
                        <input type="submit" value="Delete" class="btn btn-danger ml-1 mr-1" />
                        @*
                            <button class="btn btn-danger ml-1 mr-1" asp-controller="Task" asp-action="Delete" asp-route-taskId="@Model.TaskId">
                                Delete
                            </button>
                        *@
                        <button class="btn btn-secondary ml-1 mr-1" asp-controller="Goal" asp-action="Details" asp-route-goalId="@Model.GoalId" formmethod="get">
                            Cancel
                        </button>
                    </form>
                </td>
            </tr>
        </tfoot>
    </table>
</fieldset>

MSSA.Canvas-Your-Goals/Views/Task/Details.cshtml
@using Step = MSSA.Canvas_Your_Goals.Models.Step
@model MSSA.Canvas_Your_Goals.Models.Task

@{
    ViewData["Title"] = "Task Details";
}

<div class="flex-row justify-content-center">
    <fieldset class="flex-div shadow">
        <legend> @ViewData["Title"] </legend>
        <table class="table-bordered table-striped table-sm">
            <tbody>
                <tr>
                    <th> Goal Name: </th>
                    <td> @Model.TaskName </td>
                </tr>
                <tr>
                    <th> Task Order: </th>
                    <td> @Model.TaskOrder </td>
                </tr>
                <tr>
                    <th> Status: </th>
                    <td> @Model.Status </td>
                </tr>
                <tr>
                    <th> Start Date: </th>
                    <td> @Model.StartDate.ToString("MM/dd/yyyy") </td>
                </tr>
                <tr>
                    <th> End Date: </th>
                    <td> @Model.EndDate?.ToString("MM/dd/yyyy") </td>
                </tr>
                <tr>
                    <th> Details: </th>
                    <td> @Model.Details </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td class="text-center" colspan="2">
                        <a class="btn btn-info ml-1 mr-1" asp-controller="Goal" asp-action="Details" asp-route-goalId="@Model.GoalId">
                            Back
                        </a>
                        <a class="btn btn-warning ml-1 mr-1" asp-controller="Task" asp-action="Edit" asp-route-taskId="@Model.TaskId">
                            Edit
                        </a>
                        <a class="btn btn-danger ml-1 mr-1" asp-controller="Task" asp-action="Delete" asp-route-taskId="@Model.TaskId">
                            Delete
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </fieldset>

    <fieldset class="flex-div shadow">
        <legend> Steps for: @Model.TaskName </legend>
        <table class="table-bordered table-striped table-sm">
            <thead>
                <tr>
                    <th class="pr-1 text-center"> Step </th>
                    <th class="pr-1 text-center"> Order </th>
                    <th class="pr-1 text-center"> Status </th>
                    <th class="pr-1 text-center"> Start Date </th>
                    <th class="pr-1 text-center"> End Date </th>
                    <th class="pr-1 text-center"> Details </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Step step in Model.Steps)
                {
                    <tr>
                        <td class="pr-1 text-center"> @step.StepName </td>
                        <td class="pr-1 text-center"> @step.StepOrder </td>
                        <td class="pr-1 text-center"> @step.Status </td>
                        <td class="pr-1 text-center"> @step.StartDate.ToString("MM/dd/yyyy") </td>
                        <td class="pr-1 text-center"> @step.EndDate?.ToString("MM/dd/yyyy") </td>
                        <td class="pr-1 text-center">
                            <a asp-controller="Step" asp-action="Details" asp-route-stepId="@step.StepId" class="btn btn-sm btn-outline-info ml-1 mr-1">
                                View
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <a asp-controller="Step" asp-action="Add" asp-route-taskId="@Model.TaskId" class="btn btn-outline-info ml-1 mr-1">Create New Step! </a>
                        @*
                            <span
                                page-model="@Model.PagingInfo"
                                page-action="Index"
                                page-class-enabled="true"
                                page-class="btn"
                                page-class-normal="btn-outline-dark"
                                page-class-selected="btn-primary"
                                class="btn-group m-1 float-right">
                            </span>
                        *@
                    </td>
                </tr>
            </tfoot>
        </table>
    </fieldset>
</div>

MSSA.Canvas-Your-Goals/Views/Task/Edit.cshtml
@model MSSA.Canvas_Your_Goals.Models.Task

@{
    ViewData["Title"] = "Edit Task";
}

<header> <partial name="LoggedInNav" /> </header>
<fieldset class="shadow centered">
    <legend> @ViewData["Title"] </legend>
    <form method="post">
        <input asp-for="TaskId" type="hidden" />
        <input asp-for="GoalId" type="hidden" />
        <table class="table-bordered table-striped table-sm">
            @if (ViewData.ModelState.ErrorCount > 0)
            {
                <thead>
                    <tr>
                        <td colspan="2">
                            <div asp-validation-summary="All"> </div>
                        </td>
                    </tr>
                </thead>
            }
            <tbody>
                <tr>
                    <th> Task Name: </th>
                    <td> <input asp-for="TaskName" /> </td>
                </tr>
                <tr>
                    <th> Task Order: </th>
                    <td> <input asp-for="TaskOrder" type="range" /> </td>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                        <select asp-for="Status">
                            <option value=""> @Model.Status </option>
                            <option value="Finished">Finished</option>
                            <option value="In Progress">In Progress</option>
                            <option value="Problem">Problem</option>
                            <option value="Waiting">Waiting</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th> Start Date: </th>
                    <td> <input asp-for="StartDate" type="date" /> </td>
                </tr>
                <tr>
                    <th> End Date: </th>
                    <td> <input asp-for="EndDate" type="date" /> </td>
                </tr>
                <tr>
                    <th> Details: </th>
                    <td> @Html.EditorFor(model => model.Details) </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td class="text-center" colspan="2">
                        <input class="btn btn-primary ml-1 mr-1" type="submit" value="Create Task!" />
                        <a class="btn btn-secondary ml-1 mr-1" asp-controller="Goal" asp-action="Details" asp-route-goalId="@Model.GoalId">
                            Cancel
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    </form>
</fieldset>